# Regression Week 5: LASSO (coordinate descent)

In this notebook, you will implement your very own LASSO solver via coordinate descent. You will:
* Write a function to normalize features
* Implement coordinate descent for LASSO
* Explore effects of L1 penalty

# Fire up graphlab create

Make sure you have the latest version of graphlab (>= 1.7)

In [1]:
import graphlab

# Load in house sales data

Dataset is from house sales in King County, the region where the city of Seattle, WA is located.

In [2]:
sales = graphlab.SFrame('kc_house_data.gl/')
# In the dataset, 'floors' was defined with type string, 
# so we'll convert them to int, before using it below
sales['floors'] = sales['floors'].astype(int) 

[INFO] 1452433635 : INFO:     (initialize_globals_from_environment:282): Setting configuration variable GRAPHLAB_FILEIO_ALTERNATIVE_SSL_CERT_FILE to C:\Users\margrami\AppData\Local\Dato\Dato Launcher\lib\site-packages\certifi\cacert.pem
1452433635 : INFO:     (initialize_globals_from_environment:282): Setting configuration variable GRAPHLAB_FILEIO_ALTERNATIVE_SSL_CERT_DIR to 
This non-commercial license of GraphLab Create is assigned to margrami221@yahoo.com and will expire on October 13, 2016. For commercial licensing options, visit https://dato.com/buy/.

[INFO] Start server at: ipc:///tmp/graphlab_server-3660 - Server binary: C:\Users\margrami\AppData\Local\Dato\Dato Launcher\lib\site-packages\graphlab\unity_server.exe - Server log: C:\Users\margrami\AppData\Local\Temp\graphlab_server_1452433635.log.0
[INFO] GraphLab Server Version: 1.7.1


If we want to do any "feature engineering" like creating new features or adjusting existing ones we should do this directly using the SFrames as seen in the first notebook of Week 2. For this notebook, however, we will work with the existing features.

# Import useful functions from previous notebook

As in Week 2, we convert the SFrame into a 2D Numpy array. Copy and paste `get_num_data()` from the second notebook of Week 2.

In [3]:
import numpy as np # note this allows us to refer to numpy as np instead 

Also, copy and paste the `predict_output()` function to compute the predictions for an entire matrix of features given the matrix and the weights:

In [4]:
def predict_output(feature_matrix, weights):
    # assume feature_matrix is a numpy matrix containing the features as columns and weights is a corresponding numpy array
    # create the predictions vector by using np.dot()
    predictions = np.dot (feature_matrix, weights)

    return(predictions)

# Normalize features
In the house dataset, features vary wildly in their relative magnitude: `sqft_living` is very large overall compared to `bedrooms`, for instance. As a result, weight for `sqft_living` would be much smaller than weight for `bedrooms`. This is problematic because "small" weights are dropped first as `l1_penalty` goes up. 

To give equal considerations for all features, we need to **normalize features** as discussed in the lectures: we divide each feature by its 2-norm so that the transformed feature has norm 1.

Let's see how we can do this normalization easily with Numpy: let us first consider a small matrix.

In [5]:
X = np.array([[3.,5.,8.],[4.,12.,15.]])
print X

[[  3.   5.   8.]
 [  4.  12.  15.]]


Numpy provides a shorthand for computing 2-norms of each column:

In [6]:
# math.sqrt(x11**2, x21**2)

norms = np.linalg.norm(X, axis=0) # gives [norm(X[:,0]), norm(X[:,1]), norm(X[:,2])] 
print norms

[  5.  13.  17.]


To normalize, apply element-wise division:

In [7]:
print X / norms # gives [X[:,0]/norm(X[:,0]), X[:,1]/norm(X[:,1]), X[:,2]/norm(X[:,2])]

[[ 0.6         0.38461538  0.47058824]
 [ 0.8         0.92307692  0.88235294]]


Using the shorthand we just covered, write a short function called `normalize_features(feature_matrix)`, which normalizes columns of a given feature matrix. The function should return a pair `(normalized_features, norms)`, where the second item contains the norms of original features. As discussed in the lectures, we will use these norms to normalize the test data in the same way as we normalized the training data. 

In [8]:
def normalize_features(feature_matrix):
    norms = np.linalg.norm(feature_matrix, axis=0)
    normalized_features = feature_matrix / norms
    return normalized_features, norms
    

To test the function, run the following:

In [9]:
features, norms = normalize_features(np.array([[3.,6.,9.],[4.,8.,12.]]))
print features
# should print
# [[ 0.6  0.6  0.6]
#  [ 0.8  0.8  0.8]]
print norms
# should print
# [5.  10.  15.]

[[ 0.6  0.6  0.6]
 [ 0.8  0.8  0.8]]
[  5.  10.  15.]


# Implementing Coordinate Descent with normalized features

We seek to obtain a sparse set of weights by minimizing the LASSO cost function
```
SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|).
```
(By convention, we do not include `w[0]` in the L1 penalty term. We never want to push the intercept to zero.)

The absolute value sign makes the cost function non-differentiable, so simple gradient descent is not viable (you would need to implement a method called subgradient descent). Instead, we will use **coordinate descent**: at each iteration, we will fix all weights but weight `i` and find the value of weight `i` that minimizes the objective. That is, we look for
```
argmin_{w[i]} [ SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|) ]
```
where all weights other than `w[i]` are held to be constant. We will optimize one `w[i]` at a time, circling through the weights multiple times.  
  1. Pick a coordinate `i`
  2. Compute `w[i]` that minimizes the cost function `SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|)`
  3. Repeat Steps 1 and 2 for all coordinates, multiple times

For this notebook, we use **cyclical coordinate descent with normalized features**, where we cycle through coordinates 0 to (d-1) in order, and assume the features were normalized as discussed above. The formula for optimizing each coordinate is as follows:
```
       ┌ (ro[i] + lambda/2)     if ro[i] < -lambda/2
w[i] = ├ 0                      if -lambda/2 <= ro[i] <= lambda/2
       └ (ro[i] - lambda/2)     if ro[i] > lambda/2
```
where
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ].
```

Note that we do not regularize the weight of the constant feature (intercept) `w[0]`, so, for this weight, the update is simply:
```
w[0] = ro[i]
```

## Effect of L1 penalty

Let us consider a simple model with 2 features:

In [10]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1 # this is how you add a constant column to an SFrame
    # add the column 'constant' to the front of the features list so that we can extract it along with the others:
    features = ['constant'] + features # this is how you combine two lists
    features_sframe = data_sframe[features] # select the columns of data_SFrame given by the features list into the SFrame features_sframe (now including constant):

    # the following line will convert the features_SFrame into a numpy matrix:
    feature_matrix = features_sframe.to_numpy()
    # assign the column of data_sframe associated with the output to the SArray output_sarray
    output_sarray = data_sframe['price']
    # the following will convert the SArray into a numpy array by first converting it to a list
    output_array = output_sarray.to_numpy()
    return(feature_matrix, output_array)

In [27]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)

Don't forget to normalize features:

In [28]:
simple_feature_matrix, norms = normalize_features(simple_feature_matrix)

We assign some random set of initial weights and inspect the values of `ro[i]`:

In [29]:
weights = np.array([1., 4., 1.])

Use `predict_output()` to make predictions on this data.

In [30]:
prediction = predict_output(simple_feature_matrix, weights)

Compute the values of `ro[i]` for each feature in this simple model, using the formula given above, using the formula:
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ]
```

*Hint: You can get a Numpy vector for feature_i using:*
```
simple_feature_matrix[:,i]
```

In [24]:
feature_matrix = simple_feature_matrix
ro =[]
ro[0] = 0
for i in range (1, len(simple_feature_matrix) + 1 ):
     # compute ro[i] = SUM[ [feature_i]*(output - prediction + weight[i]*[feature_i]) ]
    #ro_i = np.sum(feature_matrix[:,i]*(output - prediction + weights[i]*feature_matrix[:,i]))
    #ro[i] = np.sum(feature_matrix[:,i]*(output -prediction + weights[i]*feature_matrix[:,i]))
    ro[i] = i

IndexError: list assignment index out of range

***QUIZ QUESTION***

Recall that, whenever `ro[i]` falls between `-l1_penalty/2` and `l1_penalty/2`, the corresponding weight `w[i]` is sent to zero. Now suppose we were to take one step of coordinate descent on either feature 1 or feature 2. What range of values of `l1_penalty` **would not** set `w[1]` zero, but **would** set `w[2]` to zero, if we were to take a step in that coordinate? 

In [35]:
prediction=predict_output(simple_feature_matrix, weights)
ro=np.sum(simple_feature_matrix[:,1]*(output - prediction + weights[1]*simple_feature_matrix[:,1]))

In [37]:
ro/2

43969735.386495538

In [38]:
ro = [0 for i in range((simple_feature_matrix.shape)[1])]
for j in range((simple_feature_matrix.shape)[1]):    
    ro[j] = (simple_feature_matrix[:,j] * (output - prediction + (weights[j] * simple_feature_matrix[:,j]))).sum()
print ro

[79400300.034929156, 87939470.772991076, 80966698.675965652]


In [39]:
diff = abs((ro[1]*2) - (ro[2]*2))
print('λ = (%e, %e)' %((ro[2]-diff/2+1)*2, (ro[2]+diff/2-1)*2))

λ = (1.479879e+08, 1.758789e+08)


***QUIZ QUESTION***

What range of values of `l1_penalty` would set **both** `w[1]` and `w[2]` to zero, if we were to take a step in that coordinate? 

So we can say that `ro[i]` quantifies the significance of the i-th feature: the larger `ro[i]` is, the more likely it is for the i-th feature to be retained.

## Single Coordinate Descent Step

Using the formula above, implement coordinate descent that minimizes the cost function over a single feature i. Note that the intercept (weight 0) is not regularized. The function should accept feature matrix, output, current weights, l1 penalty, and index of feature to optimize over. The function should return new weight for feature i.

In [31]:
def lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty):
    # compute prediction  
    prediction = predict_output(feature_matrix, weights)
    # compute ro[i] = SUM[ [feature_i]*(output - prediction + weight[i]*[feature_i]) ]
    ro_i = np.sum(feature_matrix[:,i]*(output - prediction + weights[i]*feature_matrix[:,i]))

    if i == 0: # intercept -- do not regularize
        new_weight_i = ro_i 
    elif ro_i < -l1_penalty/2.:
        new_weight_i = ro_i + (l1_penalty/2) 
    elif ro_i > l1_penalty/2.:
        new_weight_i = ro_i - (l1_penalty/2)
    else:
        print "ro = 0, valor de l1_penalty: %g" % l1_penalty
        new_weight_i = 0.
    
    return new_weight_i

In [32]:
l1_penalties = [1.4e8, 1.64e8, 1.73e8, 1.9e8, 2.3e8]

for i in range (1 , len(simple_feature_matrix)):
    for l1_pen in l1_penalties:
        new_weight = lasso_coordinate_descent_step(i, simple_feature_matrix, output, weights, l1_pen)
    

ro = 0, valor de l1_penalty: 1.9e+08
ro = 0, valor de l1_penalty: 2.3e+08
ro = 0, valor de l1_penalty: 1.64e+08
ro = 0, valor de l1_penalty: 1.73e+08
ro = 0, valor de l1_penalty: 1.9e+08
ro = 0, valor de l1_penalty: 2.3e+08


IndexError: index 3 is out of bounds for axis 1 with size 3

To test the function, run the following cell:

In [34]:
# should print 0.425558846691
import math
print lasso_coordinate_descent_step(1, np.array([[3./math.sqrt(13),1./math.sqrt(10)],[2./math.sqrt(13),3./math.sqrt(10)]]), 
                                   np.array([1., 1.]), np.array([1., 4.]), 0.1)

0.425558846691


## Cyclical coordinate descent 

Now that we have a function that optimizes the cost function over a single coordinate, let us implement cyclical coordinate descent where we optimize coordinates 0, 1, ..., (d-1) in order and repeat.

When do we know to stop? Each time we scan all the coordinates (features) once, we measure the change in weight for each coordinate. If no coordinate changes by more than a specified threshold, we stop.

For each iteration:
1. As you loop over features in order and perform coordinate descent, measure how much each coordinate changes.
2. After the loop, if the maximum change across all coordinates is falls below the tolerance, stop. Otherwise, go back to step 1.

Return weights

**IMPORTANT: when computing a new weight for coordinate i, make sure to incorporate the new weights for coordinates 0, 1, ..., i-1. One good way is to update your weights variable in-place. See following pseudocode for illustration.**
```
for i in range(len(weights)):
    old_weights_i = weights[i] # remember old value of weight[i], as it will be overwritten
    # the following line uses new values for weight[0], weight[1], ..., weight[i-1]
    #     and old values for weight[i], ..., weight[d-1]
    weights[i] = lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
    
    # use old_weights_i to compute change in coordinate
    ...
```

In [60]:

def lasso_cyclical_coordinate_descent(feature_matrix, output, initial_weights, l1_penalty, tolerance):
    print "in lasso_cyclical"
    weights= initial_weights.copy()
    
    converged = False
    #max_changed = 0
    while not converged:
        print "in while loop"
        max_changed = 0
        for i in range(len(weights)):
            print'i is:'+ str(i)
            old_weights_i = weights[i]
            print "old_weights_i" 
            print old_weights_i
            weights[i] = lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
            change_i = np.abs(old_weights_i - weights[i])
            print "change_i is:" +str(change_i)
            if change_i > max_changed:
                max_changed = change_i
                print "max_changed :" + str(max_changed)
        #end forloop      
        if max_changed < tolerance:              
            converged = True 
    return weights
            
    

Using the following parameters, learn the weights on the sales dataset. 

In [62]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
initial_weights = np.zeros(3)
l1_penalty = 1e7
tolerance = 1.0

First create a normalized version of the feature matrix, `normalized_simple_feature_matrix`

In [63]:
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)
(normalized_simple_feature_matrix, simple_norms) = normalize_features(simple_feature_matrix) # normalize features

Then, run your implementation of LASSO coordinate descent:

In [82]:
weights = lasso_cyclical_coordinate_descent(normalized_simple_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

in lasso_cyclical
in while loop
i is:0
old_weights_i
0.0
change_i is:79400304.6581
max_changed :79400304.6581
i is:1
old_weights_i
0.0
change_i is:10305258.636
i is:2
old_weights_i
0.0
change_i is:299724.114499
in while loop
i is:0
old_weights_i
79400304.6581
change_i is:9138168.3665
max_changed :9138168.3665
i is:1
old_weights_i
10305258.636
change_i is:8642336.99872
i is:2
old_weights_i
-299724.114499
change_i is:299724.114499
in while loop
i is:0
old_weights_i
70262136.2916
change_i is:8194809.40937
max_changed :8194809.40937
i is:1
old_weights_i
18947595.6347
change_i is:7213612.45102
i is:2
old_weights_i
0.0
change_i is:0.0
in while loop
i is:0
old_weights_i
62067326.8822
change_i is:6598905.03827
max_changed :6598905.03827
i is:1
old_weights_i
26161208.0858
change_i is:6036579.86894
i is:2
old_weights_i
0.0
change_i is:0.0
in while loop
i is:0
old_weights_i
55468421.8439
change_i is:5522173.1943
max_changed :5522173.1943
i is:1
old_weights_i
32197787.9547
change_i is:5051601.6436

In [83]:
weights

array([ 21624998.36636292,  63157246.78545421,         0.        ])

In [84]:
def get_residual_sum_of_squares(model,outcome):
    # First get the predictions
    predictions = model
    residuals = np.zeros((len(model)))
    for j in range (0, len(model)):
        # Then compute the residuals/errors
        residuals[j] = (outcome[j] - predictions[j])**2

        # Then square and add them up
        
    RSS = sum(residuals)
    return(RSS)    

In [87]:
prediction = predict_output(simple_feature_matrix, weights)

21613

In [89]:
RSS = get_residual_sum_of_squares(prediction, output)

In [92]:
print 'RSS = %g' % RSS

RSS = 1.63049e+15


***QUIZ QUESTIONS***
1. What is the RSS of the learned model on the normalized dataset?
2. Which features had weight zero at convergence? BEDROOMS

# Evaluating LASSO fit with more features

Let us split the sales dataset into training and test sets.

In [41]:
train_data,test_data = sales.random_split(.8,seed=0)

Let us consider the following set of features.

In [42]:
all_features = ['bedrooms',
                'bathrooms',
                'sqft_living',
                'sqft_lot',
                'floors',
                'waterfront', 
                'view', 
                'condition', 
                'grade',
                'sqft_above',
                'sqft_basement',
                'yr_built', 
                'yr_renovated']

First, create a normalized feature matrix from the TRAINING data with these features.  (Make you store the norms for the normalization, since we'll use them later)

In [97]:
my_output = 'price'
(all_feature_matrix, output) = get_numpy_data(train_data, all_features, my_output)
normalized_all_feature_matrix, norms = normalize_features(all_feature_matrix)

In [51]:
normalized_all_feature_matrix

array([[ 0.00758447,  0.00652117,  0.0033687 , ...,  0.        ,
         0.00752148,  0.        ],
       [ 0.00758447,  0.00652117,  0.00757957, ...,  0.0057043 ,
         0.0075061 ,  0.03707954],
       [ 0.00758447,  0.00434745,  0.0033687 , ...,  0.        ,
         0.00743684,  0.        ],
       ..., 
       [ 0.00758447,  0.00652117,  0.00842175, ...,  0.        ,
         0.00772924,  0.        ],
       [ 0.00758447,  0.00652117,  0.00842175, ...,  0.        ,
         0.00771   ,  0.        ],
       [ 0.00758447,  0.00434745,  0.00252652, ...,  0.        ,
         0.00772539,  0.        ]])

First, learn the weights with `l1_penalty=1e7`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e7`, you will need them later.

In [98]:
initial_weights = np.zeros(14)
l1_penalty = 1e7
tolerance = 1.0

In [99]:
weights1e7 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

in lasso_cyclical
in while loop
i is:0
old_weights_i
0.0
change_i is:71114625.7528
max_changed :71114625.7528
i is:1
old_weights_i
0.0
change_i is:0.0
i is:2
old_weights_i
0.0
change_i is:3743972.43192
i is:3
old_weights_i
0.0
change_i is:5271064.34696
i is:4
old_weights_i
0.0
change_i is:0.0
i is:5
old_weights_i
0.0
change_i is:0.0
i is:6
old_weights_i
0.0
change_i is:7173100.28481
i is:7
old_weights_i
0.0
change_i is:7025132.06643
i is:8
old_weights_i
0.0
change_i is:5530804.65692
i is:9
old_weights_i
0.0
change_i is:0.0
i is:10
old_weights_i
0.0
change_i is:394565.584395
i is:11
old_weights_i
0.0
change_i is:2242690.39485
i is:12
old_weights_i
0.0
change_i is:2160960.47386
i is:13
old_weights_i
0.0
change_i is:0.0
in while loop
i is:0
old_weights_i
71114625.7528
change_i is:5024356.36869
max_changed :5024356.36869
i is:1
old_weights_i
0.0
change_i is:0.0
i is:2
old_weights_i
3743972.43192
change_i is:1896957.47295
i is:3
old_weights_i
5271064.34696
change_i is:4305009.73889
i is:4
o

In [100]:
weights1e7

array([ 24429600.60933314,         0.        ,         0.        ,
        48389174.35227978,         0.        ,         0.        ,
         3317511.16271982,   7329961.9848964 ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ])

***QUIZ QUESTION***

What features had non-zero weight in this case?

Next, learn the weights with `l1_penalty=1e8`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e8`, you will need them later.

In [113]:
initial_weights = np.zeros(14)
l1_penalty = 1e8
tolerance = 1.0
weights1e8 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

in lasso_cyclical
in while loop
i is:0
old_weights_i
0.0
change_i is:71114625.7528
max_changed :71114625.7528
i is:1
old_weights_i
0.0
change_i is:0.0
i is:2
old_weights_i
0.0
change_i is:0.0
i is:3
old_weights_i
0.0
change_i is:0.0
i is:4
old_weights_i
0.0
change_i is:0.0
i is:5
old_weights_i
0.0
change_i is:0.0
i is:6
old_weights_i
0.0
change_i is:0.0
i is:7
old_weights_i
0.0
change_i is:0.0
i is:8
old_weights_i
0.0
change_i is:0.0
i is:9
old_weights_i
0.0
change_i is:0.0
i is:10
old_weights_i
0.0
change_i is:0.0
i is:11
old_weights_i
0.0
change_i is:0.0
i is:12
old_weights_i
0.0
change_i is:0.0
i is:13
old_weights_i
0.0
change_i is:0.0
in while loop
i is:0
old_weights_i
71114625.7528
change_i is:0.0
i is:1
old_weights_i
0.0
change_i is:0.0
i is:2
old_weights_i
0.0
change_i is:0.0
i is:3
old_weights_i
0.0
change_i is:0.0
i is:4
old_weights_i
0.0
change_i is:0.0
i is:5
old_weights_i
0.0
change_i is:0.0
i is:6
old_weights_i
0.0
change_i is:0.0
i is:7
old_weights_i
0.0
change_i is:0.0
i

In [115]:
weights1e8

array([ 71114625.75280938,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ])

***QUIZ QUESTION***

What features had non-zero weight in this case?

Finally, learn the weights with `l1_penalty=1e4`, on the training data. Initialize weights to all zeros, and set the `tolerance=5e5`.  Call resulting weights `weights1e4`, you will need them later.  (This case will take quite a bit longer to converge than the others above.)

In [116]:
initial_weights = np.zeros(14)
l1_penalty = 1e4
tolerance = 5e5

weights1e4 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)



in lasso_cyclical
in while loop
i is:0
old_weights_i
0.0
change_i is:71114625.7528
max_changed :71114625.7528
i is:1
old_weights_i
0.0
change_i is:3956380.1017
i is:2
old_weights_i
0.0
change_i is:4963442.4709
i is:3
old_weights_i
0.0
change_i is:5351785.20245
i is:4
old_weights_i
0.0
change_i is:1029778.70128
i is:5
old_weights_i
0.0
change_i is:8770183.36166
i is:6
old_weights_i
0.0
change_i is:12531492.3845
i is:7
old_weights_i
0.0
change_i is:10818930.3004
i is:8
old_weights_i
0.0
change_i is:8852214.38705
i is:9
old_weights_i
0.0
change_i is:3691006.4869
i is:10
old_weights_i
0.0
change_i is:6552708.56441
i is:11
old_weights_i
0.0
change_i is:2946362.53467
i is:12
old_weights_i
0.0
change_i is:11587978.8267
i is:13
old_weights_i
0.0
change_i is:3043479.31193
in while loop
i is:0
old_weights_i
71114625.7528
change_i is:656582.579069
max_changed :656582.579069
i is:1
old_weights_i
3956380.1017
change_i is:2468988.04934
max_changed :2468988.04934
i is:2
old_weights_i
4963442.4709
cha

In [117]:
weights1e4

array([ 77779073.91265225, -22884012.25023361,  15348487.08089996,
        92166869.69883074,  -2139328.0824278 ,  -8818455.54409492,
         6494209.73310655,   7065162.05053198,   4119079.21006765,
        18436483.52618776, -14566678.54514342,  -5528348.75179426,
       -83591746.20730537,   2784276.46012858])

***QUIZ QUESTION***

What features had non-zero weight in this case?

## Rescaling learned weights

Recall that we normalized our feature matrix, before learning the weights.  To use these weights on a test set, we must normalize the test data in the same way.

Alternatively, we can rescale the learned weights to include the normalization, so we never have to worry about normalizing the test data: 

In this case, we must scale the resulting weights so that we can make predictions with *original* features:
 1. Store the norms of the original features to a vector called `norms`:
```
features, norms = normalize_features(features)
```
 2. Run Lasso on the normalized features and obtain a `weights` vector
 3. Compute the weights for the original features by performing element-wise division, i.e.
```
weights_normalized = weights / norms
```
Now, we can apply `weights_normalized` to the test data, without normalizing it!

Create a normalized version of each of the weights learned above. (`weights1e4`, `weights1e7`, `weights1e8`).

In [118]:
weights1e8_normalized = weights1e8 / norms
weights1e7_normalized = weights1e7 / norms
weights1e4_normalized = weights1e4 / norms

To check your results, if you call `normalized_weights1e7` the normalized version of `weights1e7`, then:
```
print normalized_weights1e7[3]
```
should return 161.31745624837794.

In [119]:
print weights1e7_normalized[3]

161.317456248


## Evaluating each of the learned models on the test data

Let's now evaluate the three models on the test data:

In [108]:
(test_feature_matrix, test_output) = get_numpy_data(test_data, all_features, 'price')

Compute the RSS of each of the three normalized weights on the (unnormalized) `test_feature_matrix`:

In [120]:
prediction1e8 = predict_output(test_feature_matrix, weights1e8_normalized)
RSS_w1e8 = get_residual_sum_of_squares(prediction1e8, test_output)
print 'RSS para weights1e8 = %g ' % RSS_w1e8

RSS para weights1e8 = 5.37166e+14 


In [121]:
prediction1e7 = predict_output(test_feature_matrix, weights1e7_normalized)
RSS_w1e7 = get_residual_sum_of_squares(prediction1e7, test_output)
print 'RSS para weights1e7 = %g ' % RSS_w1e7

RSS para weights1e7 = 2.75962e+14 


In [122]:
prediction1e4 = predict_output(test_feature_matrix, weights1e4_normalized)
RSS_w1e4 = get_residual_sum_of_squares(prediction1e4, test_output)
print 'RSS para weights1e4 = %g ' % RSS_w1e4                               

RSS para weights1e4 = 2.27781e+14 


***QUIZ QUESTION***

Which model performed best on the test data?