In [1]:
import numpy as np

In [3]:
X = np.array([[1, 1] , [2, 2]])
X

array([[1, 1],
       [2, 2]])

In [6]:
Y = np.array([[3, 3], [3, 3]])
Y

array([[3, 3],
       [3, 3]])

In [8]:
diff = X[0:len(X)] - Y[0]
diff

array([[-2, -2],
       [-1, -1]])

In [13]:
distances = np.sum(diff, axis=1)[0:18]
distances

array([-4, -2])